apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    name: nextcloud
spec:
  ports:
    - name: nextcloud
      port: 80
      targetPort: 80
      nodePort: 32275
      protocol: TCP
  selector:
    name: nextcloud
  type: NodePort