apiVersion: v1
kind: Pod
metadata:
  name: nextcloud
  labels:
    name: nextcloud
spec:
  containers:
    - name: nextcloud
      image: nextcloud
      env:
        - name: TZ
          value: Asia/Tokyo
        - name: DOMAIN
          value: 192.168.0.104
        - name: NEXTCLOUD_ADMIN_USER
          value: admin
        - name: NEXTCLOUD_ADMIN_PASSWORD
          value: password
        - name: NEXTCLOUD_UPLOAD_MAX_FILESIZE
          value: 4G
        - name: UPLOAD_MAX_FILE
          value: "20"
        - name: DB_TYPE
          value: psql
        - name: POSTGRES_HOST
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWARD
          value: password
        - name: POSTGRES_DB
          value: nextcloud_db
      ports:
        - name: nextcloud
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /var/www/html/data
          name: data
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 60
        timeoutSeconds: 1
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: nfs-nextcloud-claim1