apiVersion: v1
kind: Pod
metadata:
  name: nextcloud
  labels:
    name: nextcloud
spec:
  containers:
    - name: nextcloud
      image: nextcloud
      env:
        - name: NEXTCLOUD_ADMIN_USER
          value: admin
        - name: NEXTCLOUD_ADMIN_PASSWORD
          value: password
        - name: POSTGRES_HOST
          value: postgresql
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: nextcloud_db
      ports:
        - name: nextcloud
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /var/www/html/data
          name: nextcloud-data
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 60
        timeoutSeconds: 1
  volumes:
    - name: nextcloud-data
      persistentVolumeClaim:
        claimName: nfs-nextcloud-claim1
