apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nextcloud-pv001
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 172.31.10.4
    path: /nfs/nextcloud
