apiVersion: v1
kind: Pod
metadata:
  name: postgresql
  labels:
    name: postgresql
spec:
  containers:
    - name: postgresql
      image: postgres
      env:
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: nextcloud_db
      ports:
        - containerPort: 5432
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/postgresql
          name: data
      livenessProbe:
        tcpSocket:
          port: 5432
        initialDelaySeconds: 300
        timeoutSeconds: 5
  volumes:
    - name: data
      persistentVolumeClaim:
       claimName: nfs-nextcloud-claim1
